#+title: A New Dream
#+date: <2026-01-01 Thu 18:00>

This is my very first post!

For the past couple years I have been going over in my head what I should dedicate myself to.

I switched jobs from being an insurance agent during a critical time in the industry. I couldn't stomach the insane price points everything was going to, and I had always wanted to do something in media production, so I jumped ship.

And then I was unemployed for over a year, trying to get a job in something that I was passionate about (ideally in media production). This proved to be impossible, as the job market was (and is) on a downward spiral in favor of automation via Large Langauge Models. So settled down with a job with family.

This job wasn't bad, it was great even. Yet still this quesiton about what I should dedicate my life to was still in my head.

So like many others who haven't got a clue what they should do, I went to these fancy language models to think through the problem with me.

It essentially told me this:

#+BEGIN_SRC gemini
  "You are a Systems Director. Your "ideal purpose" is to identify where the "pipes" of society are clogged (Incentives/Coordination),
  use your technical mind to design a better "plumbing" system (Architecture), and use your expressive skills to convince the "able-minded people" to help you install it"
#+END_SRC


Now, I'm not a fan of AI's psychofantic demeanor, (I'm no Systems Direcotor) but I quite liked what we came up.

So that's the plan. Moving forward I am going to be in the business of trying to inspire change and bulding a culture around hope and egalitarianism.

This means doing research in how things operate, the system in which people operate in, and how people think about it, and formulating strategies on what could be better world.

Now, such things are not easy, I have no delusion of that. At this point, I'm facing issues that organizations spend millions of dollars with stacked workforces to solve, alone.

But hey, I was already unemployed before, and this is my life's purpose we're talking about here. I might as well try.

Such is life, we just gotta try.
