#+title: A Slight Change In Gears
#+date: <2026-01-09 Fri 08:00>
#+author: Ruben Dominguez

So it would seem that I am shifting gears a little.

When referring to my [[file:01.org][initial]] entry, I couldn't help but feel overwhelmed by the task at hand. I couldn't see myself dedicating vast amounts of hours to every pillar of the operation I wanted to tackle (Networking, Knowledge Building, ect.) while also creating a viable social media brand.

It's just so counter to the modern media landscape that is before us, which basically includes mass publications while trying to stay in tune with the algorithms that govern the visibility and success of such media.

Essentially I'm saying that media publishing online is like a fulltime job that isn't very much at all conducive to building knowledge structures for social change. Sure, the research and compiling of such information may inform what I ought to create, but I didn't really see the utility in doing these concurrently, at least not to start.

Of course, I could document my journey of learning, a sort of adventure towards competence and eventually towards change, but that wasn't the vision I had for the type of content I would have for the project.

* A call to creativity

Along with this reluctant realization, I thought about the personal meaning it instilled in me.

If I were really to dedicate myself solely to one thing, then I would at least want to have something in it for me, and I realized that that would probably not be a fulfilling endeavor for me.

I know, I haven't even really started, and I am already turning away from the initial thing I wanted to do, but in a way I am going back to the core desire that I've just about had my entire life. That being that I would create narrative stories.

I want to try my hand at creative writing, and producing videos that showcase that creative writing.

This doesn't exactly match with my mission statement, but on the other hand, it could build my online presence as a creative, and maybe in the future bolster the attention I would like to put on social movements and the like.

Not to mention that this is something that I think would energize me to actually do all that research on the side and one day come back to it in full force.

I will still probably follow along with my development of knowledge and ideas for social change on my [[https:youtube.com/@BehindRuben][personal YouTube channel]], so I am in a way still working towards my initial goal, just differently.

I hope that I can soon get started on this branded endeavor, as it's still something that excites me. I'll just move along in, let's say, an unofficial manner.

Thanks for reading; I'll be seeing you really soon.
