#+title: The Train Has Left The Station
#+date: <2026-01-23 Fri 14:00>
#+author: Ruben Dominguez

Well, I've been at it for about two weeks now, and I've certainly got a rythm going.

Really, it's going better than I imagined. I've got a BehindRuben video brewing. Just some editing that I will likely finish the next time it's on my calendar. I started the beginning process of my 'Proactive Society' book that I've already started to collect research and sources for. I've started doing the creative writing that I wanted to do; Two stories, one for my substack and another that I think I will self-publish in book marketplaces. I've even been able to keep at my responsibilities on the side.

The substack story is an idea I had a while ago, not that novel, but I thought it was an interesting premise. I'm 3000 words in, and I'm kinda hitting a wall in that regard. I think it's to be expected, as I'm coming up to the climax. It just seems so lackluster, like I've misled the reader into thinking something epic was going to happen.

This sort of doubt, as I've learned from various videos on the matter of being a creative writter, I think is normal, but it's still a nasty thing to deal with.

Other than that, my other biggest challenge is how I'm going to make time for all my other projects. I've completely neglected the efforts at modeling a system over on profileprofiles.com.

The setup I have now, is that I dedicate whole days to certain projects, with gaps in between. Like so:

| Day 1  | Narrative Story         |
| Day 2  | Narrative Story         |
| Day 3  | Narrative Story         |
| Day 4  | BehindRuben             |
| Day 5  | Cooperative Distraction |
| Day 7  | Narrative Story         |
| Day 8  | Narrative Story         |
| Day 9  | Narrative Story         |
| Day 10 | Marketing on the side   |

It's for the most part working, and keeping things simple. Simplicity is the king of productivity. As you can see, my creative writing is getting the prioritization I think I should have. Still, it's a shame that it looks like I'm not going to be able to really power through the other projects.

I can always be faster, though these days, considering my health, I'm just not able to really do that. I know how I get when I go weeks on end grinding. It leads to burnout and a cynical outlook that I'm not interested in falling into any time soon.

In all honesty, I'm on a narrative day, and I'm procrastinating by writing this article, but it looks like I'm almost done, so that excuse is running its course.

It's times like these where I look to the ancient knowledge of the [[https://en.wikipedia.org/wiki/Bhagavad_Gita][Bahgavad Gita]], which emphasized not thinking about the outcome of what you plan to accomplish, but focus on the process of doing so. That hasn't really been a problem till now. I really want to finish this substack story, but maybe if I just keep that in mind, I can get through it.

That's all for today.

Thanks for reading,
